# Generated by Django 4.2.7 on 2023-11-15 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sucursal.sucursal')),
                ('address_0', models.TextField(db_column='address')),
                ('country', models.TextField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
