# Generated by Django 4.2.7 on 2023-11-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '__first__'),
        ('sucursal', '__first__'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sucursal.sucursal')),
                ('address_0', models.TextField(db_column='address')),
                ('country', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empleado.empleado')),
            ],
        ),
    ]
