# Generated by Django 4.2.7 on 2023-11-23 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_surname', models.CharField(max_length=200)),
                ('customer_dni', models.CharField(db_column='customer_DNI', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('branch_id', models.IntegerField()),
                ('tipo_cliente', models.CharField(max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
