# Generated by Django 4.2.7 on 2023-11-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_surname', models.CharField(max_length=200)),
                ('customer_dni', models.CharField(db_column='customer_DNI', max_length=10)),
                ('dob', models.TextField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
