# Generated by Django 4.2.7 on 2023-11-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='customer_dni',
            field=models.CharField(db_column='customer_DNI', max_length=8),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('GOLD', 'Cliente Gold'), ('BLACK', 'Cliente Black'), ('CLASSIC', 'Cliente Classic')], max_length=10),
        ),
    ]
