# Generated by Django 4.2.7 on 2023-11-23 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_number', models.TextField()),
                ('cvv', models.TextField()),
                ('issuance_date', models.TextField()),
                ('expiration_date', models.TextField()),
                ('type', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
            ],
        ),
    ]
