# Generated by Django 4.2.7 on 2023-11-27 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestamo', models.CharField(choices=[('hipotecario', 'Préstamo Hipotecario'), ('prendario', 'Préstamo Prendario'), ('personal', 'Préstamo Personal')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
    ]
