# Generated by Django 4.2.7 on 2023-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('id_tarjeta', models.IntegerField()),
                ('brand', models.TextField()),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
    ]
